# ### RUMMIKUB
# NUMBERS_PER_COLOR = 13
# HAND_SIZE = 14
# TARGET = 30
# COLORS = ['BLUE', 'BLACK', 'RED', 'YELLOW']
# NUM_COLORS = len(COLORS)
# DUPLICATE_TILES = 2
# UNIQUE_TILE_COUNT = NUM_COLORS * NUMBERS_PER_COLOR
# MIN_SET_SIZE = 3
# MAX_SET_SIZE = 13

# DUMMYKUB
NUMBERS_PER_COLOR = 7
HAND_SIZE = 8
TARGET = 11

COLORS = ['BLUE', 'RED', 'YELLOW']
NUM_COLORS = len(COLORS)

DUPLICATE_TILES = 2
UNIQUE_TILE_COUNT = NUM_COLORS * NUMBERS_PER_COLOR

MIN_SET_SIZE = 3
MAX_SET_SIZE = 13
